# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-regel-periode
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
  kafka:
    pool: "{{kafka.pool}}"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  env:
    - name: JAVA_OPTS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=50.0 -XX:ActiveProcessorCount=4
  envFrom:
    - secret: dp-regel-periode-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
