apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8080
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  kafka:
    pool: nav-prod
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  secureLogs:
    enabled: true
