apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-periode
spec:
  vault:
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvdp-regel-periode
  secureLogs:
    enabled: true