apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-periode
spec:
  env:
    - name:  KAFKA_BOOTSTRAP_SERVERS
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"