apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-periode
spec:
  env:
    - name: BEHOV_TOPIC
      value: "privat-dagpenger-behov-v1-q2"
    - name: APPLICATION_ID
      value: "dagpenger-regel-periode-q2"