apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: q2
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  env:
    - name: BEHOV_TOPIC
      value: "privat-dagpenger-behov-v1-q2"
    - name: APPLICATION_ID
      value: "dagpenger-regel-periode-q2"
    - name: KAFKA_TOPIC
      value: "privat-dagpenger-behov-v2-q2"
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/{{service_user}}
        mountPath: /var/run/secrets/nais.io/service_user
