apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-periode
spec:
  env:
    - name: BEHOV_TOPIC
      value: "privat-dagpenger-behov-v1-q2"
    - name: APPLICATION_ID
      value: "dagpenger-regel-periode-q2"
    - name: KAFKA_TOPIC
      value: "privat-dagpenger-behov-v2-q2"
  vault:
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvdp-regel-periode